version: "3.9"

services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app/app
      - /mnt/data/ptw-uploads:/mnt/data/ptw-uploads

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ptw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"  # Using port 5434 to avoid conflict with existing PostgreSQL
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ptw"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ptw_pg:/var/lib/postgresql/data

volumes:
  ptw_pg:
